# Generated by Django 5.0.1 on 2024-01-12 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('first_name', 'email')},
        ),
    ]
